PROJECT_DIR = example_maps_headless


#-- Windows ----------------------------------------------------------------------------------------
# SYSTEM_INCLUDEPATHS  += C:\FreeImage\Dist\x64
# LIBRARYPATHS         += C:\FreeImage\Dist\x64

#Download:
#http://glew.sourceforge.net/index.html
# SYSTEM_INCLUDEPATHS  += "C:/GLEW/glew-2.1.0/include/"
# LIBRARYPATHS         += "C:/GLEW/glew-2.1.0/lib/Release/x64/"
# LIBRARYPATHS         += "C:/GLEW/glew-2.1.0/bin/Release/x64/"

#Download:
#https://www.glfw.org/download
# SYSTEM_INCLUDEPATHS += "C:/Users/PC/projects/external/glfw/glfw-3.3.8.bin.WIN64/include"
# LIBRARYPATHS        += "C:/Users/PC/projects/external/glfw/glfw-3.3.8.bin.WIN64/lib-vc2019"
